MODULE_SUB_DIR = src/common/
MODULE_SUB_DIR += src/time/
MODULE_SUB_DIR += src/file/
MODULE_SUB_INC = inc

MODULE_NAME = HAL
MODULE_CUR_PATH = $(CURDIR)
include $(ROOT_PATH)/Rules/platform.mk
#模块库mk  调试执行程序mk
include $(ROOT_PATH)/Rules/module.mk