MODULE_SUB_DIR = Notification



MODULE_SUB_INC = Notification

MODULE_NAME = framework
MODULE_CUR_PATH = $(CURDIR)
include $(ROOT_PATH)/Rules/platform.mk
#模块库mk  调试执行程序mk
include $(ROOT_PATH)/Rules/module.mk